# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJ5nIsCKRqU_M5xUdfXDSif5-f04nip9
"""

import streamlit as st
import folium
from folium.plugins import Draw, MeasureControl
from streamlit_folium import st_folium
import rasterio
from rasterio.plot import reshape_as_image
from rasterio.warp import calculate_default_transform, reproject, Resampling
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from branca.element import Template, MacroElement
import os

# Configuração da página do Streamlit
st.set_page_config(page_title="Dashboard Espacial", layout="wide")
st.title("🗺️ Meu Dashboard Espacial Interativo")
st.markdown("Análise de ortomosaico, lotes e edificações.")

# Caminhos locais (relativos à pasta do projeto)
orto_original = 'dados/ORTOMOSAICO.tif'
orto_wgs84 = 'orto_wgs84.tif'
orto_transparente = 'ortomosaico_transparente.png'
caminho_lotes = 'dados/lotes.geojson'
caminho_edificacoes = 'dados/edificacoes.geojson'

# Verificar se os arquivos de dados existem
if not os.path.exists(orto_original):
    st.error(f"Por favor, coloque o arquivo {orto_original} na pasta 'dados/'")
    st.stop()

# =========================================================
# PROCESSAMENTO DO RASTER (Com cache para não travar o app)
# =========================================================
@st.cache_data
def processar_raster():
    dst_crs = 'EPSG:4326'

    # Reprojeção
    with rasterio.open(orto_original) as src:
        transform, width, height = calculate_default_transform(
            src.crs, dst_crs, src.width, src.height, *src.bounds
        )
        kwargs = src.meta.copy()
        kwargs.update({
            'crs': dst_crs,
            'transform': transform,
            'width': width,
            'height': height
        })

        with rasterio.open(orto_wgs84, 'w', **kwargs) as dst:
            for i in range(1, src.count + 1):
                reproject(
                    source=rasterio.band(src, i),
                    destination=rasterio.band(dst, i),
                    src_transform=src.transform,
                    src_crs=src.crs,
                    dst_transform=transform,
                    dst_crs=dst_crs,
                    resampling=Resampling.nearest
                )

    # Conversão para RGBA (Transparência)
    with rasterio.open(orto_wgs84) as src:
        img = src.read([1, 2, 3])
        bounds = src.bounds
        nodata_val = src.nodata if src.nodata is not None else 0

    img = reshape_as_image(img)
    is_nodata = (img[:, :, 0] == nodata_val) & (img[:, :, 1] == nodata_val) & (img[:, :, 2] == nodata_val)
    is_white_border = (img[:, :, 0] >= 250) & (img[:, :, 1] >= 250) & (img[:, :, 2] >= 250)

    alpha = np.ones((img.shape[0], img.shape[1]), dtype=np.uint8) * 255
    alpha[is_nodata | is_white_border] = 0

    img_norm = img.astype(float)
    for i in range(3):
        min_v = np.percentile(img_norm[:,:,i], 2)
        max_v = np.percentile(img_norm[:,:,i], 98)
        img_norm[:,:,i] = np.clip((img_norm[:,:,i] - min_v) / (max_v - min_v + 1e-5) * 255, 0, 255)
    img_norm = img_norm.astype(np.uint8)

    img_rgba = np.dstack((img_norm, alpha))
    plt.imsave(orto_transparente, img_rgba)

    return [[bounds.bottom, bounds.left], [bounds.top, bounds.right]]

# Executa o processamento pesado
with st.spinner("Processando imagens de satélite (isso pode demorar na primeira execução)..."):
    limites_orto = processar_raster()

# =========================================================
# CRIAÇÃO DO MAPA
# =========================================================
centro_lat = (limites_orto[0][0] + limites_orto[1][0]) / 2
centro_lon = (limites_orto[0][1] + limites_orto[1][1]) / 2

m = folium.Map(
    location=[centro_lat, centro_lon],
    tiles='https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
    attr='Google',
    name='Satélite (Google)',
    zoom_start=15
)

# Camadas de Fundo
folium.TileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', attr='Esri', name='Satélite (Esri)', overlay=False).add_to(m)
folium.TileLayer('OpenStreetMap', name='OpenStreetMap', overlay=False).add_to(m)
folium.TileLayer("CartoDB positron", name="Mapa Claro (CartoDB)", overlay=False).add_to(m)

# Adicionando o Ortomosaico
folium.raster_layers.ImageOverlay(
    image=orto_transparente,
    bounds=limites_orto,
    opacity=1.0,
    name="Ortomosaico Limpo",
    overlay=True
).add_to(m)

# --- LOTES ---
if os.path.exists(caminho_lotes):
    gdf_lotes = gpd.read_file(caminho_lotes).to_crs(epsg=4326)
    colunas_lotes = [col for col in gdf_lotes.columns if col != 'geometry']
    popup_lotes = folium.features.GeoJsonPopup(fields=colunas_lotes, aliases=colunas_lotes, labels=True)
    folium.GeoJson(gdf_lotes, name="Lotes", style_function=lambda x: {'color': '#000000', 'fillOpacity': 0, 'weight': 2}, popup=popup_lotes).add_to(m)

# --- EDIFICAÇÕES ---
if os.path.exists(caminho_edificacoes):
    gdf_edificacoes = gpd.read_file(caminho_edificacoes).to_crs(epsg=4326)
    colunas_edificacoes = [col for col in gdf_edificacoes.columns if col != 'geometry']
    popup_edificacoes = folium.features.GeoJsonPopup(fields=colunas_edificacoes, aliases=colunas_edificacoes, labels=True)
    folium.GeoJson(gdf_edificacoes, name="Edificações", style_function=lambda x: {'fillColor': '#ADD8E6', 'color': '#00008B', 'fillOpacity': 0.5, 'weight': 1}, popup=popup_edificacoes).add_to(m)

# Legenda HTML
template_legenda = """
{% macro html(this, kwargs) %}
<div id='maplegend' class='maplegend' style='position: fixed; z-index:9999; border:2px solid grey; background-color:rgba(255, 255, 255, 0.9); border-radius:6px; padding: 10px; font-size:14px; right: 20px; bottom: 20px; font-family: Arial, sans-serif;'>
  <div style='font-weight: bold; margin-bottom: 8px; text-align: center;'>Legenda</div>
  <ul style='margin: 0; padding: 0; list-style: none;'>
    <li><span style='display: inline-block; width: 25px; height: 3px; background: #000000; margin-right: 8px;'></span>Lotes</li>
    <li><span style='display: inline-block; width: 23px; height: 13px; background: #ADD8E6; border: 1px solid #00008B; margin-right: 8px;'></span>Edificações</li>
  </ul>
</div>
{% endmacro %}
"""
macro = MacroElement()
macro._template = Template(template_legenda)
m.get_root().add_child(macro)

# Ferramentas
MeasureControl(position='topleft', primary_length_unit='meters', primary_area_unit='sqmeters').add_to(m)
Draw(export=True, filename='dados_coletados.geojson', position='topleft').add_to(m)
folium.LayerControl().add_to(m)

# RENDEREZAR NO STREAMLIT
st_folium(m, width=1100, height=600, returned_objects=[])